// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:44e730dd-e45e-4cff-9bd8-ac31db6901cc",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_LEWuuynMV",
    "aws_user_pools_web_client_id": "3ivb31u2f1rmvib92ggnr4mv6p",
    "aws_appsync_graphqlEndpoint": "https://phoiu4c37zeknarhpxpgrxslkq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "appb9f961390f8543db926d0556804e4c29",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "app-20190102150016-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d3mejk79s1qm11.cloudfront.net"
};


export default awsmobile;
